### ISSUE TITLE
cmdline mode doesn't work

### ISSUE THREAD

**Issue by alanorth** [compgen-io/sbs#1]
The arguments are trimmed when I try to use command line mode:

```console
$ ./sbs submit -- ls /tmp
3
$ cat .sbs/sbs.3/script 
#!/bin/sh
ls%                       
```

Otherwise, sbs is exactly what I'm looking for: a simple, single-file (with no deps) queue for running stuff in order. Bonus that you implemented SLURM niceties like `-afterok`! ;)

**Comment by mbreese** [comment]
Thanks! The idea was to have a single/simple batch job running tool to use for developing larger pipeline tools (see: compgen-io/cgpipe). But it also has the effect of being able to run pipelines on other systems that aren't tied into a larger scheduler (like SLURM). I used to just install SGE on my laptop, but that's a bit difficult to manage. SBS also makes it easier to just spin up an AWS EC2 VM and process data w/o a lot of extra work.

-- should be fixed now.

**Comment by alanorth** [comment]
Thank you! For now I ended up using [pueue](https://github.com/Nukesor/pueue). Very cool project also. Very fast and featureful up until 10,000 jobs (hah!).

I will re-visit sbs next time I need something lightweight.
